// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpbRb7cBoio66utrY3sjx3P1KxOp8WkFM',
    appId: '1:54645768090:web:86967338ed7076be4b8423',
    messagingSenderId: '54645768090',
    projectId: 'flutter-video-conference-d6300',
    authDomain: 'flutter-video-conference-d6300.firebaseapp.com',
    storageBucket: 'flutter-video-conference-d6300.appspot.com',
    measurementId: 'G-G9Z1GD9JJB',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAOoXWgngI01N37P1MYHjZWxzvr7Sty31Y',
    appId: '1:54645768090:android:3a7fba04a83968db4b8423',
    messagingSenderId: '54645768090',
    projectId: 'flutter-video-conference-d6300',
    storageBucket: 'flutter-video-conference-d6300.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiloPS_j32i1CinwAY2ejlPd9kZVE2aBI',
    appId: '1:54645768090:ios:cca30661312d88194b8423',
    messagingSenderId: '54645768090',
    projectId: 'flutter-video-conference-d6300',
    storageBucket: 'flutter-video-conference-d6300.appspot.com',
    iosBundleId: 'com.example.videoConfrenceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiloPS_j32i1CinwAY2ejlPd9kZVE2aBI',
    appId: '1:54645768090:ios:cca30661312d88194b8423',
    messagingSenderId: '54645768090',
    projectId: 'flutter-video-conference-d6300',
    storageBucket: 'flutter-video-conference-d6300.appspot.com',
    iosBundleId: 'com.example.videoConfrenceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpbRb7cBoio66utrY3sjx3P1KxOp8WkFM',
    appId: '1:54645768090:web:fee6a793ebb7fbe14b8423',
    messagingSenderId: '54645768090',
    projectId: 'flutter-video-conference-d6300',
    authDomain: 'flutter-video-conference-d6300.firebaseapp.com',
    storageBucket: 'flutter-video-conference-d6300.appspot.com',
    measurementId: 'G-XYX41GZVMN',
  );
}
